### ISSUE TITLE
React server-side retina detection

### ISSUE THREAD

**Issue by Yuripetusko** [halt-hammerzeit/javascript-retina-detect#2]
Hi, do you know any solution to detect retina when using react server-side rendering? Currently it displays `1` on server side and `2` on client side

**Comment by halt-hammerzeit** [comment]
Yes, of course it does.
The only thing you have on server side is `User-Agent` but I'd say that parsing `User-Agent` is a hack and should be avoided, and i guess `User-Agent` doesn't have any information about device model or pixel ratio.

**Comment by Yuripetusko** [comment]
Ok thanks, will switch to `srcset` then..

**Comment by halt-hammerzeit** [comment]
Yes, that's the recommended way to do it.
I have my layout in `em`s so `srcset` won't work for me but if you're using `px`s then it can work for you.
